---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Business Applications:
    - Website:
        href: http://jetsoms.co.uk/
        description: Website
    - The Hub:
        href: https://hub.jetsoms.co.uk
        description: Hub

- Business Resources:
    - Microsoft:
        href: http://localhost/
        description: Email Provider

- Third Party Links:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
